_target_: src.datamodules.BaseDataModule
train_dataset:
  _target_: src.datamodules.datasets.ImageMaskDataset
  images_dir: ${data_root}/cvc_colondb_polyp/images/
  masks_dir: ${data_root}/cvc_colondb_polyp/masks/
  caps_file: ${data_root}/cvc_colondb_polyp/anns/train.json
  img_size: ${img_size}
  transforms: ${train_img_transforms}
  

val_dataset:
  _target_: src.datamodules.datasets.ImageMaskDataset
  images_dir: ${data_root}/cvc_colondb_polyp/images/
  masks_dir: ${data_root}/cvc_colondb_polyp/masks/
  caps_file: ${data_root}/cvc_colondb_polyp/anns/val.json
  img_size: ${img_size}
  transforms: ${val_img_transforms}

test_dataset:
  - _target_: src.datamodules.datasets.ImageMaskDataset
    images_dir: ${data_root}/cvc_colondb_polyp/images/
    masks_dir: ${data_root}/cvc_colondb_polyp/masks/
    caps_file: ${data_root}/cvc_colondb_polyp/anns/test.json
    img_size: ${img_size}
    transforms: ${test_img_transforms}
  - _target_: src.datamodules.datasets.ImageMaskDataset
    images_dir: ${data_root}/cvc_colondb_polyp/images/
    masks_dir: ${data_root}/cvc_colondb_polyp/masks/
    caps_file: ${data_root}/cvc_colondb_polyp/anns/train.json
    img_size: ${img_size}
    transforms: ${test_img_transforms}

batch_size: 16
train_val_split: [0.8, 0.2]
num_workers: 4
pin_memory: True