_target_: src.models.BaseModule
net:
  _target_: src.models.CRIS
  clip_pretrain: pretrained/RN50.pt
  word_len: 77
  fpn_in: [512, 1024, 1024]
  fpn_out: [256, 512, 1024]
  vis_dim: 512
  word_dim: 1024
  num_layers: 3
  num_head: 8
  dim_ffn: 2048
  dropout: 0.2
  intermediate: false
  freeze_encoder: true
  cris_pretrain: pretrained/cris_best_single.pth

loss_fn: 
  _target_: monai.losses.DiceCELoss
  lambda_dice: 1.5
  lambda_ce: 1.0
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.001
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.3
  patience: 5